guid: 00b09d0100a80b41 
video_mode: 640x480_mono8
frame_rate: 30
frame_id: point
camera_info_url: pointgrey2000_cali.yaml
reset_on_open: true
use_ros_time: true
bayer_pattern: "rggb"
bayer_method: ""
auto_brightness: 3
brightness: 154
auto_exposure: 3
exposure: 31
auto_gain: 3
gain: 6.041
auto_shutter: 3
shutter: 0.01
auto_white_balance: 3
white_balance_BU: 737
white_balance_RV: 573
